export const log: {
    (...data: any[]): void;
    (message?: any, ...optionalParams: any[]): void;
};
export function json(arg: any): string;
export function JL(arg: any): void;
export function isEmpty(coll: any): boolean;
export function collapse(coll: any, sep?: string, crumbs?: any[], acc?: {}): {};
export function prune(coll: any, sep?: string, acc?: {}): {};
export function augment(props: any): any;
export const diff: ((acc: any, cur: any) => any)[];
export function squish(coll: any): any[];
export function squash(coll: any): any[];
export function collect_by_path(path: any, entries?: any[]): {};
export function aggregate_by_key(reports?: any[]): {};
export function coll_by_path_aggregate(path?: any[], entries?: any[]): {};
export function apply_kv_ops(key_reduction_map?: {}): (aggregate?: {}) => {};
export function coll_aggregator_sender(data: any): {};
export function averaged(agr_coll: any): {};
export function metric_name(k: any): "Succeeded (#)" | "Delivered (%)" | "Opened (%)" | "Clicked (%)" | "Deleted (%)" | "Engaged (%)" | "Impressions (#)" | "Sent (#)" | "Delivered (#)" | "Opens (#)" | "Unique Opens (#)" | "Clicks (#)" | "Unique Clicks (#)" | "(#)";
