// https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types
export const MIMETypes = {
    // text
    txt: "text/plain",
    css: "text/css",
    csv: "text/csv",
    html: "text/html",
    xml: "text/xml",
    ics: "text/calendar",
    // images
    tiff: "image/tiff",
    jpeg: "image/jpeg",
    jpg: "image/jpeg",
    gif: "image/gif",
    png: "image/png",
    bmp: "image/bmp",
    svg: "image/svg+xml",
    webp: "image/webp",
    // audio
    weba: "audio/webm",
    aac: "audio/aac",
    mp3: "audio/mpeg",
    wav: "audio/wav",
    oga: "audio/ogg",
    opus: "audio/opus",
    // video
    webm: "video/webm",
    mp4: "video/mp4",
    ogv: "video/ogg",
    avi: "video/x-msvideo",
    ts: "video/mp2t",
    mpeg: "video/mpeg",
    json: "application/json",
    jsonld: "application/ld+json",
    // docs
    rtf: "application/rtf",
    pdf: "application/pdf",
    // microsoft
    doc: "application/msword",
    docx: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    xls: "application/vnd.ms-excel",
    xlsx: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    ppt: "application/vnd.ms-powerpoint",
    pptx: "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    // other
    odp: "application/vnd.oasis.opendocument.presentation",
    ods: "application/vnd.oasis.opendocument.spreadsheet",
    odt: "application/vnd.oasis.opendocument.text",
    ico: "image/vnd.microsoft.icon",
    // compressed
    rar: "application/vnd.rar",
    zip: "application/zip",
    "7z": "application/x-7z-compressed",
};
